D5DaysPrepLib/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls', namespace='students')),
    path('api/', include('students.api.urls', namespace='api')),
]

students/api/urls.py
from django.urls import path
from . import views

app_name = 'students'
urlpatterns = [
    path(
        'students/',
        views.StudentListView.as_view(),
        name='student_list'
    ),
    path(
        'students/<pk>/',
        views.StudentDetailView.as_view(),
        name='student_detail'
    ),
]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'
urlpatterns = [
    # Student views
    path('', views.student_list, name ='student_list'),
    path('<int:id>/',views.student_detail, name ='student_detail'),
]

books/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from students.models import Student


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    author_id = models.CharField(max_length=100)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=15)

    def __str__(self):
        return self.first_name
    
class Book(models.Model):
    isbn = models.CharField(max_length=13)
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.CharField(max_length=100)
    date_of_publish = models.DateField(max_length=100)
    quantity = models.PositiveIntegerField()
    

    def __str__(self):
        return self.title


class Borrowing(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='borrowed_books')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='borrow_records')
    borrow_date = models.DateTimeField(auto_now_add=True)
    return_date = models.DateTimeField()
    returned = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.student} borrowed {self.book}"

students/models.py
from django.contrib.auth.models import User
from django.db import models

class Student(models.Model):
    regno = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=15)


    def __str__(self):
        return self.first_name

books/views.py
from django.shortcuts import render

# Create your views here.

students/api/views.py
from rest_framework import generics
from students.api.serializers import StudentSerializer
from students.models import Student


class StudentListView(generics.ListAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer

class StudentDetailView(generics.RetrieveAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer

students/views.py
from django.shortcuts import render # Remove this line when using shortcut
from django.http import Http404 # Remove this line when using shortcut
from django.shortcuts import get_object_or_404, render
from .models import Student


# Display a list of all students
def student_list(request):
    students = Student.objects.all()
    return render(request, 'student/list.html',{'students':students})


'''
# Display a single Student
def student_detail(request, id):
    try:
        student = Student.objects.get(id=id)
    except Student.DoesNotExist:
        raise Http404("Student with the specified ID was not found!")
    return render(
        request,
        'student/detail.html',
        {'student': student}
    )

'''

# Display a single Student with Shortcut 404 Error
def student_detail(request, id):
   student = get_object_or_404(Student,id=id)
   return render(
        request,
        'student/detail.html',
        {'student': student}
    )

students/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/student.css' %}" rel="stylesheet">
</head>
<body>
    <div class="navbar">
        <div class="logo">
            <img src="{% static 'images/logo.png' %}" alt="Elib App Logo">
            <div class="title">Elib App</div>
        </div>
        <div class="avatar">
            <img src="{% static 'images/avatar.png' %}" alt="User Avatar">
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

students/templates/student/detail.html
{% extends "base.html" %}
{% block title %}{{ student.first_name }} {{ student.last_name }}{% endblock %}
{% block content %}
<div class="container">
    <h1>{{ student.first_name }} {{ student.last_name }}</h1>
    <div class="student-details">
        <p><strong>RegNo:</strong> {{ student.regno }}</p>
        <p><strong>First Name:</strong> {{ student.first_name }}</p>
        <p><strong>Last Name:</strong> {{ student.last_name }}</p>
        <p><strong>Email:</strong> {{ student.email }}</p>
        <p><strong>Phone:</strong> {{ student.phone }}</p>
    </div>
</div>
{% endblock %}

students/templates/student/list.html
{% extends "base.html" %}
{% block title %}All Students{% endblock %}

{% block content %}
    <h1>All Students</h1>
    <table>
        <thead>
            <tr>
                <th>RegNo</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Phone</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <td>
                    <a href="{% url 'students:student_detail' student.id %}">
                        {{ student.regno }}
                    </a>
                </td>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.phone }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}